# Generated by Django 3.0.4 on 2020-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id_news', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('title_news', models.CharField(max_length=50)),
                ('des_news', models.CharField(max_length=1580)),
                ('auteur_news', models.CharField(max_length=50)),
                ('image_news1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_news2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_news3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
